### ISSUE TITLE
github pages 主页按钮跳转错误

### ISSUE THREAD

**Issue by songdaochuanshu** [yesmore/Different-UI#5]
"快速上手"和"项目简介" 按钮链接错误
![image](https://user-images.githubusercontent.com/81367559/145201918-e490132e-9608-4dca-9cf6-c6fc05720878.png)

**Comment by yesmore** [comment]
> "快速上手"和"项目简介" 按钮链接错误 ![image](https://user-images.githubusercontent.com/81367559/145201918-e490132e-9608-4dca-9cf6-c6fc05720878.png)

谢谢提醒，已修复。
> 昨天重构了一下，这地方忘改了 ^_^

**Comment by songdaochuanshu** [comment]
😁
